### PR TITLE
meson: allow disabling tests

### PR DESCRIPTION
**Pull request by otavio**

### CODE REVIEW

**Review by dgibson — CHANGES_REQUESTED** [review]
This needs a much more substantial commit message.  What does this allow that's different from just not running `meson test`?

**Review by alyssais — CHANGES_REQUESTED** [review]
This would make the tests be enabled by default when cross compiling, which would cause Meson to fail to configure.

**Comment by eli-schwartz** [comment]
Failing to configure sounds odd -- unless you don't have an exe_wrapper configured (wine, qemu-user, etc. for running cross-built executables against cross-built libraries).

**Comment by alyssais** [comment]
> unless you don't have an exe_wrapper configured

That's what I mean, indeed.  (We don't have an exe wrapper configured by default in Nixpkgs, because qemu is a big build dependency, and we don't run tests for cross builds anyway.)

**Review by elmarco — APPROVED** [review]

**Comment by dgibson** [comment]
Merged, thanks.

**Pull request closed without merging**
