### PR TITLE
start of /rename-node/ support

### PR DESCRIPTION
**Pull request by galak**
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

### CODE REVIEW

**Comment by galak** [comment]
@dgibson the lex/yacc for the subnode case here isn't correct, but not sure how to fix it.  Any help would be appreciated.

**Comment by dgibson** [comment]
Uh... difficult to answer that without some more context on what you're trying to accomplish here.

**Comment by galak** [comment]
The idea is there 2 use cases I had in mind:

1. There are a number of cases we've seen in which there is an IP block that can be configured to be either a UART, I2C, or SPI.  So being able to do something:

```
sercom5: sercom@4500000 {
   ...
};

/rename-node/ &sercom5 i2c@4500000;
```

2. There are cases in which the `reg` might get redefined for a node and than having `rename-node` allows us to fix the node name to match the `reg` property.

**Comment by galak** [comment]
> Uh... difficult to answer that without some more context on what you're trying to accomplish here.

I was trying to mimic what existed for `/delete-node/`.

**Comment by galak** [comment]
@dgibson curious why you closed this.  You never responded to my comments on what I was trying to accomplish.

**Comment by dgibson** [comment]
Oh.. looks like renaming the master branch to main has auto-closed it :/.

**Pull request closed without merging**
