### PR TITLE
pylibfdt: Use python.extension_module()

### PR DESCRIPTION
**Pull request by ernestask**
This commit avoid using deprecated setuptools utilities and builds the module directly using Meson.

### CODE REVIEW

**Comment by ernestask** [comment]
I did some quick sanity checking by replacing the module and running `make check`, but it turns out that https://github.com/dgibson/dtc/pull/108 was causing tests to not run.

**Comment by dgibson** [comment]
With this patch meson builds fail for me with lots of errors from swig.

We also still get warnings when building with make because of deprecated setuptools.  I'd prefer to avoid diverging how the module is built between make and meson if we can.

**Comment by ernestask** [comment]
The thing about build systems is that they are not supposed to mimic one another. If you want to use Meson like Make, then it’s best to drop support for it.

**Comment by ernestask** [comment]
But feel free to close this if you disagree, I can maintain a fork with these changes.

**Comment by dgibson** [comment]
> The thing about build systems is that they are not supposed to mimic one another. If you want to use Meson like Make, then it’s best to drop support for it.

It's not a question of wanting to use meson like make, it's a question of (confidently) producing similar results.  What I'm worried about here is the possibility of subtle incompatibilities in the python package as produced by meson versus as produced by setuptools.

**Pull request closed without merging**
